### ISSUE TITLE
q2-ghost-tree installation problem

### ISSUE THREAD

**Issue by TWubet** [JTFouquier/q2-ghost-tree#1]
Dear Jennifer,
while installing q2-ghost-tree to the qiime2 version 2022.8, I got the error message
NameError: Duplicate view registration ('AlignedRNAFASTAFormat') defined in plugins: 'ghost-tree' and 'types'. Though I followed the suggestion to update the ghost-tree version as suggested by Kegga Evans ( see https://forum.qiime2.org/t/q2-ghost-tree-installation-problem/24079). the error remains the same.

Could you please help in solving this duplicate view registration error or issue?
thanks for your help

**Comment by splaisan** [comment]
Hi Jennifer,
same here but with the latest qiime 2024.2
cheers

```
$ qiime ghost-tree
QIIME is caching your current deployment for improved performance. This may take a few moments and should only happen once per deployment.
Traceback (most recent call last):
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/q2cli/util.py", line 279, in get_plugin_manager
    return qiime2.sdk.PluginManager.reuse_existing()
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/qiime2/sdk/plugin_manager.py", line 58, in reuse_existing
    raise UninitializedPluginManagerError
qiime2.sdk.plugin_manager.UninitializedPluginManagerError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/bin/qiime", line 11, in <module>
    sys.exit(qiime())
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/click/core.py", line 1682, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/click/core.py", line 1729, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/q2cli/commands.py", line 100, in get_command
    plugin = self._plugin_lookup[name]
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/q2cli/commands.py", line 76, in _plugin_lookup
    import q2cli.core.cache
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/q2cli/core/cache.py", line 285, in <module>
    CACHE = DeploymentCache()
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/q2cli/core/cache.py", line 61, in __init__
    self._state = self._get_cached_state(refresh=refresh)
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/q2cli/core/cache.py", line 107, in _get_cached_state
    self._cache_current_state(current_requirements)
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/q2cli/core/cache.py", line 205, in _cache_current_state
    state = self._get_current_state()
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/q2cli/core/cache.py", line 253, in _get_current_state
    plugin_manager = q2cli.util.get_plugin_manager()
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/q2cli/util.py", line 291, in get_plugin_manager
    return qiime2.sdk.PluginManager()
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/qiime2/sdk/plugin_manager.py", line 67, in __new__
    self._init(add_plugins=add_plugins)
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/qiime2/sdk/plugin_manager.py", line 107, in _init
    self.add_plugin(plugin, package, project_name,
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/qiime2/sdk/plugin_manager.py", line 136, in add_plugin
    self._integrate_plugin(plugin)
  File "/opt/miniconda3/envs/qiime2-amplicon-2024.2/lib/python3.8/site-packages/qiime2/sdk/plugin_manager.py", line 178, in _integrate_plugin
    raise NameError(
NameError: Duplicate view registration ('AlignedRNAFASTAFormat') defined in plugins: 'ghost-tree' and 'types'
```
